In [9]:
import pickle
import numpy as np
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import PorterStemmer
import string

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\paulb\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\paulb\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
def transform_text(texts):
    transformed_texts = []
    for text in texts:
        text = text.lower()   # lower casing
        text = nltk.word_tokenize(text)  # tokenization
        y = []
        for i in text:   # remove special characters
            if i.isalnum():
                y.append(i)
        text = y.copy()
        y.clear()
        for i in text:   # removing stopwords
            if i not in stopwords.words("english") :
                y.append(i)
        ps = PorterStemmer()  # for stemming
        text = y.copy()
        y.clear()
        for i in text:
            y.append(ps.stem(i))
        transformed_texts.append(" ".join(y))
        
    transformed_texts = np.array(transformed_texts)
    return np.array(transformed_texts)

In [4]:
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

In [15]:
model.predict(["Some of the concepts used in projects were beyond the scope of what was taught."])

array([1])

In [16]:
model.predict(["In general the course content is superficial and lacks continuity, in part due to the segmentation of course content. Also lacking, in my opinion, are examples of original code based on practical real world examples that can be downloaded and used as a starting point for student experimentation. Some of the code that was presented came from a site well known to Python programmers. Learning Python from that site or similar ones would have been more efficient and consumed less time."])

array([1])

In [18]:
model.predict(["It's okay but lecturer needs better communication skills in English language"])

array([1])

In [19]:
model.predict(["video quality and voice quality both are good and the lecture all so explaining everything very well so I'm so interested to see upcoming videos"])

array([0])

In [25]:
model.predict(["I'm actually building and mapping different concepts together.\
I remade my own version of the die simulator and I used the datetime library and also wrote into a text file.I built it again \
and it's beautiful.This dictionary app, I am feeling excited about it already."])

array([1])

In [26]:
model.predict(["Very good and learnable for my Carrer. I love this course a lot. Thank you so much for your effort."])

array([0])